import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.net.URL;
import java.nio.file.Paths;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App extends Application {

    public static void main(String[] args) {
        launch(args);
//        String address = "";
//        int port = 6789;
//
//        if (!args[0].isEmpty()) {
//            System.out.println("Address entered is " + args[0]);
//            address = args[0];
//        }
//
//        if (!args[1].isEmpty()) {
//            System.out.println("Port entered is " + args[1]);
//            port = Integer.parseInt(args[1]);
//        }
//
//        if (args[2].equals("-c")) {
//            Client client = new Client(address, port);
//            client.start();
//        } else {
//            Server server = new Server();
//            server.start();
//        }
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        URL url = Paths.get("src/main/java/resources/main.fxml").toUri().toURL();
        Parent root = FXMLLoader.load(url);
        primaryStage.setTitle("Chatroom");
        primaryStage.setScene(new Scene(root, 300, 275));
        primaryStage.show();
    }
}
